### ISSUE TITLE
0.004 if no $dk_length provided for verify_hex errors with Use of uninitialized value in foreach loop entry at /path/PBKDF2/Tiny.pm line 138

### ISSUE THREAD

**Issue by tontsa** [dagolden/PBKDF2-Tiny#1]
Line 138 says:
    for my $offset ( 0 .. $dk_length ) {

So seems it does 0 compares and results $match == 1 on every string.

**Comment by dagolden** [comment]
Thanks for the report.  Fixed and shipped to CPAN.
